#!/bin/bash
set -euo pipefail

REF=$(git rev-parse HEAD)
trap "git reset --hard $REF" EXIT

grep -v ^public .gitignore > x
mv x .gitignore

git add public/
git commit -m "Updating gh-pages" public

git subtree split --prefix public/ -b gh-pages
git push -f origin gh-pages:gh-pages
