#!/bin/sh
set -eu
REPO="https://discordianfish:$GITHUB_TOKEN@github.com/discordianfish/blog.git"

temp=$(mktemp -d)
trap "rm -r '$temp'" EXIT
git clone -b gh-pages "$REPO" "$temp"
cd "$temp"
tar -xvf -
git add .

git config --global user.email "circle@5pi.de"
git config --global user.name "Johannes 'fish' Ziemke"

git commit -m "Updating gh-pages"
git push -f origin gh-pages:gh-pages
