version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: &cache_restore
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run: &docker_load
          name: Load Docker image layer cache
          command: |
            set -euo pipefail
            docker load -i /caches/app.tar || true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - restore_cache: *cache_restore
      - run: *docker_load
      - add_ssh_keys:
          fingerprints:
            - "35:8d:bf:85:a5:8f:d5:d1:b2:e4:13:1e:3b:14:cf:1e"
      - run:
          name: Deploy to gh-pages
          command: cat $HOME/.ssh/id_rsa_358dbf85a58fd5d1b2e4131e3b14cf1e 
            | docker run -i app run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
