name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - run: git lfs pull
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true # Required for cache
          load: true # Required to make image available to docker run
          tags: ghcr.io/discordianfish/blog:${{ github.sha }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Copy
        run: docker run --user root:root -v $PWD/out:/out ghcr.io/discordianfish/blog:${{ github.sha }} cp -r public/ /out/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out/public
